Updated gems, fixed issues with rakes

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -3,6 +3,11 @@ set -euo pipefail
 IFS=$'\n\t'
 set -vx
 
+if [[ ! -f ".env" ]]; then
+  echo "Failed - Missing .env file. Did you forget to create/sym link it?"
+  exit 1
+fi
+
 bundle install
 bundle exec rake db:drop
 
